""" How to run: change into dir: marketplace/example
    Run using `snakemake`.
    For different running options, e.g., dryrun, specifying number of cores, etc., read documentation here:
    https://snakemake.readthedocs.io/en/v5.1.4/executable.html

    Sweeping through friction params

"""

import infosys.utils as utils


ABS_PATH = '/N/u/...*user*/Quartz/marketplace/Friction'
DATA_PATH = os.path.join(ABS_PATH, 'data')
#TODO
CONFIG_PATH = os.path.join(ABS_PATH, "config_friction_Dec30_random_rho99_eps0.00001_FINAL")
mode='igraph'
sim_num = 10 

config_fname = os.path.join(CONFIG_PATH, 'all_configs.json')
#TODO
exp_type = "vary_friction_and_learning_and_network"
EXPS = json.load(open(config_fname,'r'))[exp_type]
#EXP_NAMES = list(EXPS.keys())#[-2:]
# get network names from config file
EXPSdict = json.load(open(config_fname,'r'))[exp_type] # full dict to get network names
# initializing key
nw = "human_network"
# using keys() and values() to extract values
EXP = [sub[nw] for sub in EXPSdict.values() if nw in sub.keys()]
EXP_NAMES = [f'{expname}+{expdict["human_network"]}' for (expname, expdict) in EXPSdict.items()]


#TODO
RUN_PATH = f'30122022_eps_00001_friction_{exp_type}_{sim_num}_runs_final'
RES_PATH = os.path.join(ABS_PATH,'results',RUN_PATH)
TRACKING_PATH = os.path.join(ABS_PATH, 'verbose',RUN_PATH)


rule all:
    input:
        expand(os.path.join(RES_PATH, '{exp_name_netw_name}.json'), exp_name_netw_name=EXP_NAMES)
        
rule run_simulation:
    input:
        network = os.path.join(DATA_PATH, "infosys_network_{networkname}"),
        configfile = os.path.join(CONFIG_PATH, exp_type, "{exp_name}.json")
    output:
        measurements = os.path.join(RES_PATH, '{exp_name}+{networkname}.json'),
        tracking = os.path.join(TRACKING_PATH, '{exp_name}+{networkname}.json.gz')
    shell: """
        python3 -m workflow.scripts.driver -i {input.network} -o {output.measurements} -v {output.tracking} --config {input.configfile} --times {sim_num} --mode {mode}
    """

rule init_net:
    input:
        #TODO
        follower = os.path.join(DATA_PATH, 'networks', '{networkname}'),
        configfile = os.path.join(DATA_PATH, 'config.json') # to get values for beta and gamma to build network

    output: os.path.join(DATA_PATH, "infosys_network_{networkname}")

    shell: """
            python3 -m workflow.scripts.init_net -i {input.follower} -o {output} --config {input.configfile} --mode {mode}
        """

